[workspace]
authors = ["Gregory Bott <greg.bott@ua.edu>"]
channels = ["conda-forge"]
name = "demo_mis501"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
marimo = ">=0.17.8,<0.18"
polars = ">=1.35.1,<2"
scikit-learn = ">=1.7.2,<2"
numpy = ">=2.3.5,<3"
pandas = "*"
matplotlib = "*"
seaborn = "*"
pyarrow = ">=22.0.0,<23"
